package gr.netmechanics.jmix.tinymce.component;

/**
 * @author Panos Bariamis (pbaris)
 */
public enum TinyMceButton implements TinyMceEnum {
    SEPARATOR("|"),
    NEW_TOOLBAR("+"),

    ACCORDION("accordion"),
    ALIGN_CENTER("aligncenter"),
    ALIGN_JUSTIFY("alignjustify"),
    ALIGN_LEFT("alignleft"),
    ALIGN_NONE("alignnone"),
    ALIGN_RIGHT("alignright"),
    ANCHOR("anchor"),
    BACKCOLOR("backcolor"),
    BLOCKQUOTE("blockquote"),
    BLOCKS("blocks"),
    BOLD("bold"),
    BULLETS_LIST("bullist"),
    CANCEL("cancel"),
    CHARACTER_MAP("charmap"),
    COPY("copy"),
    CODE("code"),
    CODE_SAMPLE("codesample"),
    CUT("cut"),
    EMOTICONS("emoticons"),
    FONT_FAMILY("fontfamily"),
    FONT_SIZE("fontsize"),
    FONT_SIZE_INPUT("fontsizeinput"),
    FORECOLOR("forecolor"),
    FULLSCREEN("fullscreen"),
    H1("h1"),
    H2("h2"),
    H3("h3"),
    H4("h4"),
    H5("h5"),
    H6("h6"),
    HELP("help"),
    HR("hr"),
    IMAGE("image"),
    INDENT("indent"),
    INSERT_DATETIME("insertdatetime"),
    LINK("link"),
    ITALIC("italic"),
    LANGUAGE("language"),
    LINE_HEIGHT("lineheight"),
    LTR("ltr"),
    MEDIA("media"),
    NEW_DOCUMENT("newdocument"),
    NON_BREAKING("nonbreaking"),
    NUMBERS_LIST("numlist"),
    OPEN_LINK("openlink"),
    OUTDENT("outdent"),
    PAGE_BREAK("pagebreak"),
    PASTE("paste"),
    PASTE_TEXT("pastetext"),
    PREVIEW("preview"),
    PRINT("print"),
    QUICK_IMAGE("quickimage"),
    QUICK_LINK("quicklink"),
    QUICK_TABLE("quicktable"),
    REDO("redo"),
    REMOVE("remove"),
    REMOVE_FORMAT("removeformat"),
    RESTORE_DRAFT("restoredraft"),
    SAVE("save"),
    SELECT_ALL("selectall"),
    SEARCH_REPLACE("searchreplace"),
    RTL("rtl"),
    STRIKETHROUGH("strikethrough"),
    STYLES("styles"),
    SUBSCRIPT("subscript"),
    SUPERSCRIPT("superscript"),
    TABLE("table"),
    TABLE_CELL_PROPERTIES("tablecellprops"),
    TABLE_COPY_ROW("tablecopyrow"),
    TABLE_CUT_ROW("tablecutrow"),
    TABLE_DELETE("tabledelete"),
    TABLE_DELETE_COL("tabledeletecol"),
    TABLE_DELETE_ROW("tabledeleterow"),
    TABLE_INSERT_DIALOG("tableinsertdialog"),
    TABLE_INSERT_COL_AFTER("tableinsertcolafter"),
    TABLE_INSERT_COL_BEFORE("tableinsertcolbefore"),
    TABLE_INSERT_ROW_AFTER("tableinsertrowafter"),
    TABLE_INSERT_ROW_BEFORE("tableinsertrowbefore"),
    TABLE_MERGE_CELLS("tablemergecells"),
    TABLE_PASTE_ROW_AFTER("tablepasterowafter"),
    TABLE_PASTE_ROW_BEFORE("tablepasterowbefore"),
    TABLE_PROPERTIES("tableprops"),
    TABLE_ROW_PROPERTIES("tablerowprops"),
    TABLE_SPLIT_CELLS("tablesplitcells"),
    TABLE_CLASS("tableclass"),
    TABLE_CELL_CLASS("tablecellclass"),
    TABLE_CELL_VALIGN("tablecellvalign"),
    TABLE_CELL_BORDER_WIDTH("tablecellborderwidth"),
    TABLE_CELL_BORDER_STYLE("tablecellborderstyle"),
    TABLE_CAPTION("tablecaption"),
    TABLE_CELL_BACKCOLOR("tablecellbackgroundcolor"),
    TABLE_CELL_BORDER_COLOR("tablecellbordercolor"),
    TABLE_ROW_HEADER("tablerowheader"),
    TABLE_COL_HEADER("tablecolheader"),
    TEMPLATE("template"),
    UNDERLINE("underline"),
    UNDO("undo"),
    UNLINK("unlink"),
    VISUAL_AID("visualaid"),
    VISUAL_BLOCKS("visualblocks"),
    VISUAL_CHARACTERS("visualchars"),
    WORD_COUNT("wordcount");

    public final String jsName;

    TinyMceButton(String jsName) {
        this.jsName = jsName;
    }

    @Override
    public String getJsName() {
        return jsName;
    }
}
